name: Create Docker image and Release PDF

on:
  push:
    branches:
      - main
    paths:
        - .github/workflows/pdflatex-docker.yml
        - latex/**
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        id: build
        run: |
          docker build -t pdflatex-europecv -f latex/Dockerfile .

      - name: Check for Docker image changes
        id: check_image
        run: |
          IMAGE_HASH=$(docker images pdflatex-europecv --format "{{.ID}}")
          echo "IMAGE_HASH=$IMAGE_HASH" >> $GITHUB_ENV

      - name: Compile LaTeX and release PDF
        run: |
          TIMESTAMP=$(date +'%Y%m%d%H%M%S')
          docker run --rm -v $GITHUB_WORKSPACE:/workspace pdflatex-europecv pdflatex -output-directory=/workspace /workspace/main.tex
          gh release create "v$TIMESTAMP" /workspace/*.pdf --title "Release PDF $TIMESTAMP" --notes "Compiled LaTeX"
          
