name: Create Docker image and Release PDF

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/pdflatex

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    on:
      push:
        branches:
          - main
        paths:
          - 'latex/Dockerfile'
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: latest
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: latex/.
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  release-pdf:
    needs: build-and-push
    if: ${{ always() }}
    on:
      push:
        branches:
          - main
        paths:
          - 'latex/cv.tex'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
      attestations: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Compile LaTeX and release PDF
        run: |
          TIMESTAMP=$(date +'%Y-%m-%d %H:%M:%S')
          VTIMESTAMP=$(date +'%Y%m%d%H%M%S')
          docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:main
          docker run --rm -v $GITHUB_WORKSPACE:/workspace ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:main pdflatex -interaction=nonstopmode -output-directory=/workspace/latex /workspace/latex/cv.tex || true
          gh release create "v$VTIMESTAMP" $GITHUB_WORKSPACE/latex/*.pdf --title "Resume $TIMESTAMP" --notes "Compiled LaTeX"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

